builds:
- id: "repotr"

  # Binary name.
  binary: repotr

  # Custom ldflags templates.
  ldflags:
  - -X github.com/chez-shanpu/reposiTree/cmd.Version={{.Version}} -X github.com/chez-shanpu/reposiTree/cmd.Revision={{.ShortCommit}}

  # GOOS list to build for.
  goos:
  - linux
  - darwin
  - windows

  # GOARCH to build for.
  goarch:
  - amd64
  - arm
  - arm64
