name: go_test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v1
    - name: go mod
      run: go mod download
    - name: install golint
      run: go get -u golang.org/x/lint/golint
    - name: TEST golint
      run: ~/go/bin/golint ./...
    - name: TEST go vet
      run: go vet ./...
    - name: TEST go test
      run: go test ./...